name: Gradle Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        uses: eskatos/gradle-build-action@v1.3.1
        with:
          args: build